
// Generated by ac_shell v5.16-s018 on Wed Nov 14 10:40:49 CST 2007.

// Restrictions concerning the use of Ambit BuildGates are covered in the
// license agreement.  Distribution to third party EDA vendors is
// strictly prohibited.

module c1908(N1, N4, N7, N10, N13, N16, N19, N22, N25, N28, N31, N34, N37, N40, N43
		, N46, N49, N53, N56, N60, N63, N66, N69, N72, N76, N79, N82, N85
		, N88, N91, N94, N99, N104, N2753, N2754, N2755, N2756, N2762, N2767
		, N2768, N2779, N2780, N2781, N2782, N2783, N2784, N2785, N2786,
		 N2787, N2811, N2886, N2887, N2888, N2889, N2890, N2891, N2892, N2899
		);

	input N1;
	input N4;
	input N7;
	input N10;
	input N13;
	input N16;
	input N19;
	input N22;
	input N25;
	input N28;
	input N31;
	input N34;
	input N37;
	input N40;
	input N43;
	input N46;
	input N49;
	input N53;
	input N56;
	input N60;
	input N63;
	input N66;
	input N69;
	input N72;
	input N76;
	input N79;
	input N82;
	input N85;
	input N88;
	input N91;
	input N94;
	input N99;
	input N104;
	output N2753;
	output N2754;
	output N2755;
	output N2756;
	output N2762;
	output N2767;
	output N2768;
	output N2779;
	output N2780;
	output N2781;
	output N2782;
	output N2783;
	output N2784;
	output N2785;
	output N2786;
	output N2787;
	output N2811;
	output N2886;
	output N2887;
	output N2888;
	output N2889;
	output N2890;
	output N2891;
	output N2892;
	output N2899;




	BUFX3 i_684(.A(n_379), .Y(n_567));
	BUFX8 i_683(.A(n_197), .Y(n_565));
	BUFX4 i_682(.A(n_510), .Y(n_563));
	BUFX3 i_681(.A(n_401), .Y(n_561));
	CLKBUFX8 i_680(.A(n_550), .Y(n_559));
	BUFX4 i_678(.A(n_383), .Y(n_555));
	NAND2X1 i_193(.A(n_422), .B(N31), .Y(n_347));
	NOR2X1 i_188(.A(N46), .B(n_424), .Y(n_342));
	NAND2X1 i_186(.A(n_423), .B(n_425), .Y(n_340));
	NOR2X1 i_184(.A(n_419), .B(n_426), .Y(n_338));
	OAI21XL i_183(.A0(N94), .A1(n_427), .B0(N82), .Y(n_337));
	NAND2X1 i_176(.A(n_435), .B(N10), .Y(n_331));
	NAND2X1 i_173(.A(n_436), .B(n_425), .Y(n_328));
	NOR2X1 i_171(.A(n_437), .B(n_434), .Y(n_326));
	NOR2X1 i_170(.A(n_439), .B(n_431), .Y(n_325));
	NOR2X1 i_163(.A(n_395), .B(N13), .Y(n_318));
	NAND2X1 i_160(.A(n_382), .B(N28), .Y(n_315));
	NAND2X1 i_156(.A(n_378), .B(N31), .Y(n_311));
	NOR2X1 i_153(.A(n_567), .B(n_555), .Y(n_308));
	NAND2X1 i_151(.A(n_444), .B(n_396), .Y(n_306));
	AOI21X1 i_144(.A0(N66), .A1(n_559), .B0(n_375), .Y(n_301));
	NOR2X1 i_139(.A(N1), .B(n_380), .Y(n_296));
	NOR2X1 i_135(.A(n_567), .B(n_384), .Y(n_292));
	NOR2X1 i_134(.A(n_385), .B(n_377), .Y(n_291));
	OAI21XL i_132(.A0(N94), .A1(n_386), .B0(N76), .Y(n_289));
	NAND2BX1 i_130(.AN(N94), .B(N69), .Y(n_287));
	NOR2X1 i_127(.A(n_555), .B(N25), .Y(n_285));
	AOI21X1 i_126(.A0(N63), .A1(n_559), .B0(n_391), .Y(n_284));
	NOR2X1 i_122(.A(n_396), .B(n_381), .Y(n_280));
	NAND2X1 i_119(.A(n_394), .B(n_397), .Y(n_277));
	NOR2X1 i_117(.A(n_393), .B(n_398), .Y(n_275));
	NAND2X1 i_115(.A(n_400), .B(n_390), .Y(n_273));
	NAND3X1 i_113(.A(n_372), .B(N94), .C(n_404), .Y(n_271));
	NAND2X1 i_111(.A(n_451), .B(N1), .Y(n_269));
	NAND2X1 i_105(.A(N10), .B(n_461), .Y(n_263));
	NAND2X1 i_102(.A(n_467), .B(N28), .Y(n_260));
	NAND2X1 i_100(.A(n_470), .B(N43), .Y(n_258));
	NAND2X1 i_98(.A(n_472), .B(N46), .Y(n_256));
	NAND2X1 i_92(.A(n_480), .B(N19), .Y(n_250));
	NAND2X1 i_90(.A(n_483), .B(N22), .Y(n_248));
	NAND2X1 i_88(.A(n_487), .B(N25), .Y(n_246));
	NAND2X1 i_86(.A(n_490), .B(N31), .Y(n_244));
	NAND2X1 i_84(.A(n_491), .B(N34), .Y(n_242));
	NAND2X1 i_82(.A(n_494), .B(N37), .Y(n_240));
	NAND2X1 i_80(.A(n_496), .B(N40), .Y(n_238));
	AOI21X1 i_79(.A0(n_456), .A1(n_452), .B0(n_549), .Y(n_236));
	OAI2BB1X1 i_78(.A0N(n_402), .A1N(n_561), .B0(n_430), .Y(n_234));
	OAI21XL i_77(.A0(n_459), .A1(n_449), .B0(n_473), .Y(n_232));
	AOI21X1 i_76(.A0(n_389), .A1(n_388), .B0(n_453), .Y(n_230));
	NOR2BX1 i_15(.AN(n_234), .B(n_236), .Y(n_229));
	NOR2BX1 i_14(.AN(n_232), .B(n_230), .Y(n_227));
	OAI22X1 i_13(.A0(n_481), .A1(n_229), .B0(n_227), .B1(n_492), .Y(n_225)
		);
	AOI211X1 i_12(.A0(n_372), .A1(n_225), .B0(n_563), .C0(n_503), .Y(n_224)
		);
	OR2X1 i_70(.A(n_399), .B(n_514), .Y(n_223));
	NAND2X1 i_69(.A(n_514), .B(n_399), .Y(n_222));
	NAND2BX1 i_68(.AN(n_386), .B(n_515), .Y(n_221));
	NAND4X1 i_67(.A(N94), .B(N76), .C(n_386), .D(n_565), .Y(n_220));
	NAND2BX1 i_66(.AN(n_427), .B(n_516), .Y(n_219));
	NAND4X1 i_65(.A(N94), .B(N82), .C(n_427), .D(n_565), .Y(n_218));
	NAND2BX1 i_64(.AN(n_415), .B(n_517), .Y(n_217));
	NAND4X1 i_63(.A(N94), .B(N85), .C(n_415), .D(n_565), .Y(n_216));
	OR2X1 i_62(.A(n_518), .B(n_438), .Y(n_215));
	NAND2X1 i_61(.A(n_518), .B(n_438), .Y(n_214));
	NOR2X1 i_59(.A(n_520), .B(n_521), .Y(n_212));
	NAND2X1 i_56(.A(n_519), .B(n_522), .Y(n_209));
	NAND2X1 i_53(.A(n_424), .B(n_444), .Y(n_206));
	AOI21X1 i_52(.A0(n_563), .A1(n_559), .B0(n_524), .Y(n_205));
	NOR2X1 i_47(.A(n_527), .B(n_445), .Y(n_200));
	OR2X1 i_46(.A(n_528), .B(n_443), .Y(n_199));
	NAND2X1 i_45(.A(n_443), .B(n_528), .Y(n_198));
	OR2X4 i_44(.A(n_503), .B(n_510), .Y(n_197));
	NAND3X1 NAND3_174(.A(n_372), .B(n_559), .C(N99), .Y(n_196));
	OAI21XL i_33(.A0(n_444), .A1(n_424), .B0(n_206), .Y(n_194));
	NOR2X1 i_00(.A(N99), .B(n_559), .Y(n_187));
	NAND2X1 NAND2_161(.A(N60), .B(n_287), .Y(n_186));
	OAI21XL NAND2_160(.A0(N94), .A1(N72), .B0(N53), .Y(n_185));
	NOR2X1 i_196(.A(N4), .B(n_418), .Y(n_350));
	OAI21XL i_201(.A0(N94), .A1(n_415), .B0(N85), .Y(n_355));
	NOR2X1 i_202(.A(n_414), .B(n_409), .Y(n_356));
	NAND2X1 i_204(.A(n_411), .B(n_413), .Y(n_358));
	NOR2X1 i_206(.A(N7), .B(n_412), .Y(n_360));
	NAND2X1 i_211(.A(n_410), .B(N34), .Y(n_365));
	AOI21X1 AND2_880(.A0(n_199), .A1(n_198), .B0(n_187), .Y(N2899));
	AOI21X1 AND2_873(.A0(n_215), .A1(n_214), .B0(n_187), .Y(N2890));
	AOI21X1 AND2_872(.A0(n_217), .A1(n_216), .B0(n_187), .Y(N2889));
	AOI21X1 AND2_871(.A0(n_219), .A1(n_218), .B0(n_187), .Y(N2888));
	AOI21X1 AND2_870(.A0(n_221), .A1(n_220), .B0(n_187), .Y(N2887));
	AOI21X1 AND2_869(.A0(n_223), .A1(n_222), .B0(n_187), .Y(N2886));
	AOI31X1 NAND2_269(.A0(n_372), .A1(N94), .A2(n_462), .B0(n_548), .Y(n_371
		));
	NAND2X1 NAND2_98(.A(N72), .B(N69), .Y(n_372));
	NOR2X1 i_149(.A(n_445), .B(n_443), .Y(n_373));
	XNOR2X1 NAND2_344(.A(N10), .B(N40), .Y(n_375));
	AOI31X1 NAND2_419(.A0(N66), .A1(n_559), .A2(n_375), .B0(n_301), .Y(n_377
		));
	XOR2X1 NAND2_342(.A(N34), .B(N37), .Y(n_378));
	OAI21XL NAND2_418(.A0(N31), .A1(n_378), .B0(n_311), .Y(n_379));
	XOR2X1 NAND2_336(.A(N4), .B(N7), .Y(n_380));
	AOI21X1 NAND2_412(.A0(N1), .A1(n_380), .B0(n_296), .Y(n_381));
	XOR2X1 NAND2_340(.A(N43), .B(N46), .Y(n_382));
	OAI21XL NAND2_416(.A0(n_382), .A1(N28), .B0(n_315), .Y(n_383));
	XOR2X1 NAND2_542(.A(n_555), .B(n_381), .Y(n_384));
	AOI21X1 NAND2_583(.A0(n_384), .A1(n_567), .B0(n_292), .Y(n_385));
	AOI21X1 NAND2_640(.A0(n_377), .A1(n_385), .B0(n_291), .Y(n_386));
	OAI31X1 NAND2_686(.A0(N94), .A1(n_386), .A2(N76), .B0(n_289), .Y(n_388)
		);
	NAND2X1 AND2_695(.A(n_388), .B(n_186), .Y(n_389));
	OAI21XL NAND2_162(.A0(N94), .A1(N72), .B0(N49), .Y(n_390));
	AOI21X1 NAND2_500(.A0(N25), .A1(n_555), .B0(n_285), .Y(n_391));
	AOI31X1 NAND2_545(.A0(N63), .A1(n_559), .A2(n_391), .B0(n_284), .Y(n_393
		));
	XNOR2X1 NAND2_251(.A(N10), .B(N22), .Y(n_394));
	XOR2X1 NAND2_338(.A(N16), .B(N19), .Y(n_395));
	AOI21X1 NAND2_415(.A0(N13), .A1(n_395), .B0(n_318), .Y(n_396));
	AOI21X1 NAND2_511(.A0(n_381), .A1(n_396), .B0(n_280), .Y(n_397));
	OAI21XL NAND2_558(.A0(n_394), .A1(n_397), .B0(n_277), .Y(n_398));
	AOI21X1 NAND2_639(.A0(n_398), .A1(n_393), .B0(n_275), .Y(n_399));
	NOR2X1 i_37(.A(n_399), .B(N94), .Y(n_400));
	OAI21X2 NAND2_684(.A0(n_400), .A1(n_390), .B0(n_273), .Y(n_401));
	NAND2X1 AND2_693(.A(n_401), .B(n_185), .Y(n_402));
	NOR2X1 i_7(.A(N88), .B(n_559), .Y(n_404));
	AOI21X1 i_2(.A0(n_271), .A1(n_196), .B0(n_402), .Y(n_406));
	NAND3X1 i_8(.A(n_388), .B(n_186), .C(n_406), .Y(n_407));
	NAND3X1 AND3_110(.A(N69), .B(N56), .C(n_559), .Y(n_409));
	XOR2X1 NAND2_305(.A(N28), .B(N43), .Y(n_410));
	OAI21XL NAND2_394(.A0(N34), .A1(n_410), .B0(n_365), .Y(n_411));
	XOR2X1 NAND2_304(.A(N16), .B(N22), .Y(n_412));
	AOI21X1 NAND2_395(.A0(N7), .A1(n_412), .B0(n_360), .Y(n_413));
	OAI21XL NAND2_442(.A0(n_413), .A1(n_411), .B0(n_358), .Y(n_414));
	AOI21X1 NAND2_496(.A0(n_409), .A1(n_414), .B0(n_356), .Y(n_415));
	OAI31X1 NAND2_601(.A0(N94), .A1(n_415), .A2(N85), .B0(n_355), .Y(n_417)
		);
	XOR2X1 NAND2_297(.A(N13), .B(N22), .Y(n_418));
	AOI21X1 NAND2_390(.A0(N4), .A1(n_418), .B0(n_350), .Y(n_419));
	NAND3BX1 AND3_137(.AN(N72), .B(N53), .C(n_550), .Y(n_421));
	XOR2X1 NAND2_298(.A(N43), .B(n_421), .Y(n_422));
	OAI21XL NAND2_393(.A0(N31), .A1(n_422), .B0(n_347), .Y(n_423));
	XOR2X1 NAND2_351(.A(N25), .B(N40), .Y(n_424));
	AOI21X1 NAND2_421(.A0(n_424), .A1(N46), .B0(n_342), .Y(n_425));
	OAI21XL NAND2_472(.A0(n_425), .A1(n_423), .B0(n_340), .Y(n_426));
	AOI21X1 NAND2_522(.A0(n_426), .A1(n_419), .B0(n_338), .Y(n_427));
	OAI31X1 NAND2_628(.A0(N94), .A1(n_427), .A2(N82), .B0(n_337), .Y(n_429)
		);
	NOR2X1 AND2_653(.A(n_429), .B(n_417), .Y(n_430));
	NAND2X1 NAND2_163(.A(n_287), .B(N56), .Y(n_431));
	NAND3X1 AND3_114(.A(N60), .B(N69), .C(n_559), .Y(n_433));
	XOR2X1 NAND2_263(.A(N37), .B(n_433), .Y(n_434));
	XOR2X1 NAND2_306(.A(N28), .B(N19), .Y(n_435));
	OAI21XL NAND2_385(.A0(N10), .A1(n_435), .B0(n_331), .Y(n_436));
	OAI21XL NAND2_488(.A0(n_425), .A1(n_436), .B0(n_328), .Y(n_437));
	AOI21X1 NAND2_539(.A0(n_437), .A1(n_434), .B0(n_326), .Y(n_438));
	NOR2X1 i_36(.A(N94), .B(n_438), .Y(n_439));
	AOI21X1 NAND2_637(.A0(n_431), .A1(n_439), .B0(n_325), .Y(n_440));
	NAND3BX1 AND3_93(.AN(N72), .B(N49), .C(n_559), .Y(n_442));
	XOR2X1 NAND2_345(.A(N1), .B(n_442), .Y(n_443));
	AOI21X1 NAND2_530(.A0(n_567), .A1(n_555), .B0(n_308), .Y(n_444));
	OAI21XL NAND2_572(.A0(n_444), .A1(n_396), .B0(n_306), .Y(n_445));
	AOI211X1 NAND2_643(.A0(n_445), .A1(n_443), .B0(n_373), .C0(N94), .Y(n_447
		));
	XNOR2X1 NAND2_682(.A(n_447), .B(N79), .Y(n_448));
	NOR2BX1 AND2_703(.AN(n_440), .B(n_448), .Y(n_449));
	NAND3BX1 AND5_717(.AN(n_407), .B(n_430), .C(n_449), .Y(n_451));
	NAND2BX1 AND2_655(.AN(n_417), .B(n_429), .Y(n_452));
	NAND2X1 AND2_701(.A(n_448), .B(n_440), .Y(n_453));
	NOR3X1 AND5_718(.A(n_407), .B(n_452), .C(n_453), .Y(n_455));
	NAND2BX1 AND2_654(.AN(n_429), .B(n_417), .Y(n_456));
	NOR3X1 AND5_719(.A(n_407), .B(n_456), .C(n_453), .Y(n_458));
	NOR2BX1 AND2_702(.AN(n_448), .B(n_440), .Y(n_459));
	NAND3BX1 AND5_720(.AN(n_407), .B(n_430), .C(n_459), .Y(n_461));
	NOR2X1 i_1(.A(N91), .B(n_559), .Y(n_462));
	NOR2X1 i_3(.A(n_371), .B(n_389), .Y(n_463));
	NOR3X1 i_10(.A(n_371), .B(n_389), .C(n_402), .Y(n_464));
	NOR2X1 AND2_704(.A(n_448), .B(n_440), .Y(n_465));
	NAND3BX1 AND5_721(.AN(n_456), .B(n_465), .C(n_464), .Y(n_467));
	NAND4X1 AND5_722(.A(n_464), .B(n_429), .C(n_417), .D(n_449), .Y(n_470)
		);
	NAND3BX1 AND5_723(.AN(n_452), .B(n_465), .C(n_464), .Y(n_472));
	NOR2BX1 AND2_709(.AN(n_186), .B(n_388), .Y(n_473));
	NAND2X1 i_9(.A(n_473), .B(n_406), .Y(n_474));
	NAND2BX1 i_245(.AN(n_452), .B(n_449), .Y(n_475));
	NOR2X1 AND5_741(.A(n_475), .B(n_474), .Y(n_476));
	NAND2BX1 i_244(.AN(n_456), .B(n_449), .Y(n_477));
	NOR2X1 AND5_742(.A(n_474), .B(n_477), .Y(n_478));
	NAND4X1 AND5_743(.A(n_473), .B(n_430), .C(n_465), .D(n_406), .Y(n_480)
		);
	NAND2BX1 i_5(.AN(n_453), .B(n_473), .Y(n_481));
	NAND4BXL AND5_744(.AN(n_481), .B(n_429), .C(n_417), .D(n_406), .Y(n_483)
		);
	NOR3BX1 i_240(.AN(n_459), .B(n_371), .C(n_452), .Y(n_485));
	NAND4X1 AND5_745(.A(n_185), .B(n_473), .C(n_485), .D(n_561), .Y(n_487)
		);
	NOR2BX1 AND2_707(.AN(n_185), .B(n_561), .Y(n_488));
	NAND3BX1 AND5_746(.AN(n_475), .B(n_463), .C(n_488), .Y(n_490));
	NAND3BX1 AND5_747(.AN(n_477), .B(n_488), .C(n_463), .Y(n_491));
	NAND2X1 i_4(.A(n_430), .B(n_488), .Y(n_492));
	NAND3BX1 AND5_748(.AN(n_492), .B(n_463), .C(n_465), .Y(n_494));
	NAND4BXL AND5_749(.AN(n_452), .B(n_459), .C(n_488), .D(n_463), .Y(n_496)
		);
	NAND4BBX1 i_227(.AN(n_455), .BN(n_458), .C(n_461), .D(n_451), .Y(n_499)
		);
	NAND2X1 i_222(.A(n_483), .B(n_480), .Y(n_501));
	OR4X1 AND8_792(.A(n_499), .B(n_501), .C(n_476), .D(n_478), .Y(n_503));
	NAND4X1 i_233(.A(n_487), .B(n_472), .C(n_470), .D(n_467), .Y(n_506));
	AND2X1 i_229(.A(n_491), .B(n_490), .Y(n_507));
	NAND4BX2 AND8_793(.AN(n_506), .B(n_496), .C(n_494), .D(n_507), .Y(n_510)
		);
	NAND2X1 i_6(.A(N94), .B(n_197), .Y(n_513));
	NOR2X1 i_21(.A(n_390), .B(n_513), .Y(n_514));
	NAND3X1 i_23(.A(N94), .B(N76), .C(n_565), .Y(n_515));
	NAND3X1 i_25(.A(N94), .B(N82), .C(n_565), .Y(n_516));
	NAND3X1 i_27(.A(N94), .B(N85), .C(n_565), .Y(n_517));
	NOR2X1 i_29(.A(n_431), .B(n_513), .Y(n_518));
	AOI21X1 AND2_123(.A0(N88), .A1(N63), .B0(n_559), .Y(n_519));
	NOR2X1 i_39(.A(n_404), .B(n_398), .Y(n_520));
	NAND2X1 i_40(.A(n_559), .B(n_503), .Y(n_521));
	AOI21X1 NAND2_837(.A0(n_521), .A1(n_520), .B0(n_212), .Y(n_522));
	OAI2BB1X1 AND2_124(.A0N(N91), .A1N(N66), .B0(N104), .Y(n_523));
	OAI21XL AND2_595(.A0(N91), .A1(n_559), .B0(n_194), .Y(n_524));
	AOI31X1 NAND2_838(.A0(n_559), .A1(n_563), .A2(n_524), .B0(n_205), .Y(n_526
		));
	NAND3X1 i_42(.A(n_197), .B(N94), .C(N79), .Y(n_527));
	AOI21X1 NAND2_868(.A0(n_445), .A1(n_527), .B0(n_200), .Y(n_528));
	OAI21XL NAND2_794(.A0(N1), .A1(n_451), .B0(n_269), .Y(N2753));
	XOR2X1 NAND2_795(.A(N4), .B(n_455), .Y(N2754));
	XOR2X1 NAND2_796(.A(n_458), .B(N7), .Y(N2755));
	OAI21XL NAND2_797(.A0(N10), .A1(n_461), .B0(n_263), .Y(N2756));
	OAI21XL NAND2_803(.A0(N28), .A1(n_467), .B0(n_260), .Y(N2762));
	OAI21XL NAND2_808(.A0(N43), .A1(n_470), .B0(n_258), .Y(N2767));
	OAI21XL NAND2_809(.A0(N46), .A1(n_472), .B0(n_256), .Y(N2768));
	XOR2X1 NAND2_812(.A(N13), .B(n_476), .Y(N2779));
	XOR2X1 NAND2_813(.A(N16), .B(n_478), .Y(N2780));
	OAI21XL NAND2_814(.A0(N19), .A1(n_480), .B0(n_250), .Y(N2781));
	OAI21XL NAND2_815(.A0(N22), .A1(n_483), .B0(n_248), .Y(N2782));
	OAI21XL NAND2_816(.A0(N25), .A1(n_487), .B0(n_246), .Y(N2783));
	OAI21XL NAND2_817(.A0(N31), .A1(n_490), .B0(n_244), .Y(N2784));
	OAI21XL NAND2_818(.A0(N34), .A1(n_491), .B0(n_242), .Y(N2785));
	OAI21XL NAND2_819(.A0(N37), .A1(n_494), .B0(n_240), .Y(N2786));
	OAI21XL NAND2_820(.A0(N40), .A1(n_496), .B0(n_238), .Y(N2787));
	OAI221XL NOR2_828(.A0(n_492), .A1(n_481), .B0(n_224), .B1(n_551), .C0(n_559
		), .Y(N2811));
	OAI21XL NAND2_874(.A0(n_522), .A1(n_519), .B0(n_209), .Y(N2891));
	XOR2X1 NAND2_875(.A(n_526), .B(n_523), .Y(N2892));
	INVX1 i_673(.A(n_196), .Y(n_548));
	INVX1 i_674(.A(n_488), .Y(n_549));
	INVX1 i_675(.A(N104), .Y(n_550));
	INVX1 i_676(.A(N99), .Y(n_551));
endmodule
